comment: >-
  This issue was auto-closed because the issue template was not filled out.

  The ESPHome developers invest lots of time to maintain this project, so
  please at least fill out the issue template so that a bunch of standard
  questions don't need to be asked again each time.

  Thank you for taking the time to report a bug, hopefully it can be resolved soon.
issueConfigs:
- content:
  - "OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY"

caseInsensitive: false
